### ISSUE TITLE
[FEATURE] New Idea! 

### ISSUE THREAD

**Issue by ptnnx** [mrneo240/psp-homebrew-store#12]
Hello
@mrneo240 
**I have given some information below. Accept if you like.**

You should add some new?
And you should make some changes which make the attraction of the peoples।

1. **You should use some new programming like I have given the link, you can create a table tailored to you by using the same programming source.**
-https://kiiwii.codeberg.page/psp/
You can make a good one by using this new tech by looking at this site.

2. **I have created an icon installer, if you like it, keep it. Otherwise, tell me.**
![iMarkup_20210420_172500-removebg](https://user-images.githubusercontent.com/81209454/115394787-cabcc280-a200-11eb-9e2e-07a7bfc1e8fb.png)
![iMarkup_20210420_172500](https://user-images.githubusercontent.com/81209454/115394842-d8724800-a200-11eb-8c0e-9d522fdf283d.jpg)

3. **You can prepare a separate table and add it to it.**
![save-to-word-in-word](https://user-images.githubusercontent.com/81209454/115395015-08215000-a201-11eb-8516-0514929a57fb.jpeg)
Any table can be added to this method and you can add the content of Hombrew.

4. **All the things in your site should be order wise (according to alphabet). It would be good to put a sort by. You search your right site**
![iMarkup_20210420_173736](https://user-images.githubusercontent.com/81209454/115395758-de1c5d80-a201-11eb-9d52-8f28d101e4d0.jpg)
5. **If you say, I will add the link to everything in your store in https://emulation.gametechwiki.com/index.php/Emulators_on_PSP. Because I work "RDX" account.**
__________________
**New idea soooooon**

**Comment by rdx-f** [comment]
You also misunderstood me.

No I am always True

I am not cheat anyone
