### ISSUE TITLE
[FEATURE] maintenance reports

### ISSUE THREAD

**Issue by pierrelouys** [mrneo240/psp-homebrew-store#7]
Autogenerated reports containing Title, URL, Creator and Version for:

- Items with no preview image;
- Items with an empty 'Creator' field;
- Items without the 'PSP homebrew' tag;
- Potential duplicates (items with similar or identical titles).

Ideally reports would be accessible to all on a subpage of psp-dev.

**Comment by mrneo240** [comment]
part of this framework is already present, will need cleanup and basic presentation

**Comment by pierrelouys** [comment]
Just realized I can already export customized reports simply through the [archive.org API](https://archive.org/advancedsearch.php?q=collection%3Apsp-homebrew-library&fl[]=title&fl[]=creator&fl[]=description&fl[]=subject&fl[]=version&fl[]=date&fl[]=language&sort[]=titleSorter+asc&rows=10000&page=1&output=xml).
